sinnerschrader/feature-hub

tsconfig.json
Without the `inlineSources` option set to `true`, TypeScript generates source maps that depend on the existence of the original source files. We only wants to publish the js and d.ts files though. Therefore we should enable `inlineSources` by default to tell TypeScript to inline the source contents into the map files.
```diff
{
"version": 3,
"file": "async-value.js",
"sourceRoot": "",
"sources": ["../../src/feature-app-manager/async-value.ts"],
"names": [],
"mappings": ";;AAAA;IACC,oBACiB,OAAwB,EACjC,KAAc,EACd,KAAa;QAHrB,iBAMC;QALgB,YAAO,GAAP,OAAO,CAAiB;QACjC,UAAK,GAAL,KAAK,CAAS;QACd,UAAK,GAAL,KAAK,CAAQ;QAEpB,OAAO,CAAC,IAAI,CAAC,UAAA,GAAG,IAAI,OAAA,CAAC,KAAI,CAAC,KAAK,GAAG,GAAG,CAAC,EAAlB,CAAkB,CAAC,CAAC,KAAK,CAAC,UAAA,GAAG,IAAI,OAAA,CAAC,KAAI,CAAC,KAAK,GAAG,GAAG,CAAC,EAAlB,CAAkB,CAAC,CAAC …
```
=> fix(all): enable inlineSources in tsconfig to fix source maps

packages/integration-tests/tsconfig.json
First of all, we don't need them. And secondly, this reduces the webpack output when running the tests.
I would have liked to also reduce the stats that are printed, but because of the following bug, only one of the two bundled files is printed:
https://github.com/facebook/jest/issues/2441
Jest PR with a fix: https://github.com/facebook/jest/pull/6871
When the PR is merged, we could use this stats config for example:
```js
{
all: false,
assets: true,
colors: true,
timings: true
}
```
=> fix(integration-tests): do not emit declaration files (to memory-fs)

packages/history-service/src/__tests__/index.test.ts, packages/history-service/src/base-history.ts, packages/history-service/src/history-service-v1.ts, packages/history-service/src/index.ts, packages/history-service/src/root-histories.ts
1.) We need to make sure that the initial browser location has a key.
2.) We need to update root history keys when the root location is replaced.
fixes #149
=> fix(history-service): POP to initial location and replaced locations

README.md
The main motivation for the changes were on the one hand the guides on "Writing a Feature App/Service" which should show the final result right at the beginning and on the other hand the example of a Logger Feature Services for the deprecation warnings is not a good example and was therefore removed. We already show elsewhere how a Feature Service dependency can be used.
=> docs(all): improve consistency of main README

packages/core/src/feature-app-manager.ts, packages/react/src/__tests__/feature-app-container.node.test.tsx, packages/react/src/__tests__/feature-app-container.test.tsx, packages/react/src/feature-app-container.tsx
The `featureAppDefinition` argument provided to `getFeatureAppDefinition`
knows the type of the `FeatureApp`. Retain this type information by
providing it to the returned `FeatureAppScope`.
=> feat(core): retain FeatureApp type in FeatureAppDefinition

docs/guides/sharing-the-browser-history.md, packages/demos/src/history-service/root-location-transformer.ts, packages/history-service/src/__tests__/create-root-location-transformer.test.ts, packages/history-service/src/__tests__/define-history-service.node.test.ts, packages/history-service/src/__tests__/define-history-service.test.ts, packages/history-service/src/create-root-location-transformer.ts, packages/history-service/src/history-service-v1.ts, packages/history-service/src/internal/browser-consumer-history.ts, packages/history-service/src/internal/consumer-history.ts, packages/history-service/src/internal/consumer-paths.ts, packages/history-service/src/internal/history-multiplexer.ts, packages/history-service/src/internal/test-root-location-transformer.ts
- Renamed the `primaryConsumerId` property of the `RootLocationOptions` interface to `primaryConsumerUid`.
- Renamed the `consumerId` method argument to `consumerUid`.
=> feat(history-service): rename interface property and method argument

docs/guides/integrating-the-feature-hub.md, docs/guides/sharing-the-browser-history.md, docs/guides/writing-a-feature-service.md, docs/help/faq.md, packages/core/src/__tests__/feature-app-manager.test.ts, packages/core/src/__tests__/feature-service-registry.test.ts, packages/core/src/feature-app-manager.ts, packages/core/src/feature-service-registry.ts, packages/core/src/internal/create-uid.ts, packages/demos/src/amd-module-loader/index.test.ts, packages/demos/src/commonjs-module-loader/index.test.ts, packages/demos/src/history-service/integrator.tsx, packages/server-renderer/src/__tests__/index.test.ts
- Renamed the `registerProviders` method of the `FeatureServiceRegistry` to `registerFeatureServices`.
- The messages/errors logged by the `FeatureServiceRegistry` have been improved.
- The messages/errors logged by the `FeatureAppManager` have been improved.
=> feat(core): rename method and improve logging

docs/guides/integrating-the-feature-hub.md, docs/guides/sharing-npm-dependencies.md, docs/guides/sharing-the-browser-history.md, packages/core/src/__tests__/feature-app-manager.test.ts, packages/core/src/__tests__/feature-service-registry.test.ts, packages/demos/src/history-service/integrator.tsx, packages/demos/src/module-loader-amd/integrator.tsx, packages/demos/src/module-loader-commonjs/integrator.node.tsx, packages/react/src/__tests__/feature-app-container.node.test.tsx, packages/react/src/__tests__/feature-app-container.test.tsx, packages/react/src/__tests__/feature-app-loader.node.test.tsx, packages/react/src/__tests__/feature-app-loader.test.tsx, packages/react/src/feature-app-container.tsx, packages/react/src/feature-app-loader.tsx
This is in preparation for the task " Integrate Async SSR Manager into FeatureAppLoader" of #25, where the new prop `asyncSsrManager` will be added to the `FeatureAppLoader`.
=> feat(all): rename manager/registry to featureAppManager/featureServiceRegistry

packages/demos/src/async-ssr-manager/integrator.node.tsx
With the Async SSR Manager in place we don't need to preload the Feature App anymore.
=> fix(demos): do not preload Feature App in SSR demo

package.json, packages/demos/package.json, yarn.lock
Otherwise built `lib` directories are required to watch a demo.
=> build(demos): resolve tsconfig paths when watching demos

packages/demos/package.json, packages/demos/src/async-ssr-manager/feature-app.tsx, packages/demos/src/async-ssr-manager/index.test.ts, packages/demos/src/async-ssr-manager/integrator.node.tsx, packages/demos/src/async-ssr-manager/integrator.ts, packages/demos/src/async-ssr-manager/integrator.tsx, packages/demos/src/async-ssr-manager/webpack-config.ts, packages/demos/src/history-service/index.test.ts, packages/demos/src/history-service/integrator.node.tsx, packages/demos/src/module-loader-commonjs/index.test.ts, packages/demos/src/module-loader-commonjs/integrator.node.tsx, packages/demos/src/start-server.ts, packages/demos/src/watch-demo.ts
In a follow-up PR Id' like to rename the demo from `async-ssr-manager` to `ssr`.
=> feat(demos): add state serialization to async-ssr-manager demo

babel.config.js, jest.config.js, package.json, packages/history-service/src/internal/static-root-history.ts, wallaby.js, yarn.lock
This is the recommended way of Jest ≥ 24 and also gives us `jest.mock` hoisting with wallaby out of the box, without having to apply a babel transform on top of ts-jest's transform.
=> build(all): remove ts-jest, use @babel/preset-typescript instead

packages/core/src/__tests__/feature-service-registry.test.ts, packages/core/src/feature-service-registry.ts, packages/demos/src/history-service/history-consumer-definition.tsx, packages/demos/src/server-side-rendering/feature-app.tsx, packages/demos/src/server-side-rendering/integrator.node.tsx, packages/demos/src/server-side-rendering/integrator.tsx, packages/history-service/src/__tests__/define-history-service.test.ts, packages/history-service/src/define-history-service.ts
To allow for `dependencies`/`optionalDependencies` other then Feature Services, namely externals, introduce a `featureServices` key in `dependencies` and `optionalDependencies` of a `FeatureServiceConsumerDefinition` that contains the Feature Service dependency map.
=> feat(core): move Feature Service dependencies into a separate key

packages/demos/src/feature-app-in-feature-app/integrator.tsx, packages/demos/src/feature-app-in-feature-app/webpack-config.ts
This shows that `@feature-hub/react` must be defined as an external dependency when a Feature App wants to render another Feature App.
=> feat(demos): use a FeatureAppLoader in "Feature App in Feature App" demo

packages/website/siteConfig.js
=> docs(website): use Prism for syntax highlighting

packages/core/src/__tests__/feature-app-manager.test.ts, packages/core/src/feature-app-manager.ts, packages/react/src/__tests__/feature-app-container.node.test.tsx, packages/react/src/__tests__/feature-app-container.test.tsx, packages/react/src/__tests__/feature-app-loader.node.test.tsx, packages/react/src/__tests__/feature-app-loader.test.tsx
Since the `FeatureServiceRegistry` doesn't have a destroy method all actors in a Feature Hub environment have to make sure to that they don't allocate non-garbage-collectable resources that outlive a request while server-side-rendering anyway. We deemed this to be an acceptable requirement. Therefore remove the `destroy` method from the `FeatureAppManager`.
=> feat(core): remove FeatureAppManager#destroy

packages/core/src/__tests__/feature-app-manager.test.ts, packages/core/src/feature-app-manager.ts, packages/demos/src/feature-app-in-feature-app/integrator.node.tsx, packages/demos/src/feature-app-in-feature-app/integrator.tsx, packages/demos/src/history-service/integrator.node.tsx, packages/demos/src/history-service/integrator.tsx, packages/demos/src/module-loader-amd/integrator.tsx, packages/demos/src/module-loader-commonjs/integrator.node.tsx, packages/demos/src/server-side-rendering/integrator.node.tsx, packages/demos/src/server-side-rendering/integrator.tsx
When working on updating the documentation regarding externals, @fahrradflucht and I noticed, while reading the [Module Loader section](https://feature-hub.io/docs/guides/integrating-the-feature-hub#module-loader), that it probably makes more sense to make the `ExternalsValidator` optional, analogous to the optional module loader. Because only when an integrator uses the optional module loader to support loading Feature Apps via URL, it makes sense for him to also validate the externals that he provides for the separately deployed Feature Apps.
**Note:** Making the `ExternalsValidator` optional for the `FeatureServiceRegistry` as is done in a [follow-up PR](https://github.com/sinnerschrader/feature-hub/pull/343).
=> feat(core): make ExternalsValidator optional for the FeatureAppManager

packages/async-ssr-manager/src/__tests__/index.test.ts
Always use fake timers for `renderUntilCompleted` tests to avoid unwanted timeouts caused by the low `timeout` config.
=> test(async-ssr-manager): always use fake timers

packages/dom/src/feature-app-container.ts, packages/dom/src/feature-app-loader.ts
If `cutomElements.define` is called mutliple times with the same element name it throws. Since `defineFeatureAppLoader` calls `defineFeatureAppContainer` under the hood, which is something the user doesn't know, we need to guard against `feature-app-container` already being registered. 
To make the behaviour consistent I also added a guard in `defineFeatureAppLoader`.
=> fix(dom): guard against double definition

packages/history-service/package.json, packages/history-service/src/__tests__/define-history-service.node.test.ts, packages/history-service/src/__tests__/define-history-service.test.ts, packages/history-service/src/__tests__/stubbed-logger.ts, packages/history-service/src/define-history-service.ts, packages/history-service/src/internal/browser-consumer-history.ts, packages/history-service/src/internal/consumer-history.ts, packages/history-service/src/internal/create-history-multiplexers.ts, packages/history-service/src/internal/create-history-service-v1-binder.ts, packages/history-service/src/internal/history-service-context.ts, packages/history-service/src/internal/static-consumer-history.ts
The integrator can now provide the Logger Feature Service, which the History Service then uses for logging. The History Service declares the Logger Feature Service as an optional dependency, and uses `console` as a fallback logger, when the Logger Feature Service is not provided.
=> feat(history-service): use Logger Feature Service instead of console

packages/async-ssr-manager/package.json, packages/async-ssr-manager/src/__tests__/index.test.ts, packages/async-ssr-manager/src/__tests__/stubbed-logger.ts, packages/async-ssr-manager/src/index.ts, packages/async-ssr-manager/src/internal/async-ssr-manager-context.ts, packages/async-ssr-manager/src/internal/async-ssr-manager.ts
The integrator can now provide the Logger Feature Service, which the Async SSR Manager then uses for logging. The Async SSR Manager declares the Logger Feature Service as an optional dependency, and uses `console` as a fallback logger, when the Logger Feature Service is not provided.
=> feat(async-ssr-manager): use Logger Feature Service instead of console

packages/demos/src/integrator-dom/feature-app.ts, packages/demos/src/integrator-dom/index.test.ts, packages/dom/src/feature-app-container.ts
Previously Feature Apps could only render into the provided container element but would not be rendered if they replaced it. Now this is possible as well.
=> feat(dom): allow for container replacement

packages/react/src/__tests__/feature-app-container.test.tsx, packages/react/src/__tests__/feature-app-loader.test.tsx
We don't want the error logs in our test output.
=> test(react): suppress react's error boundary development logs

.gitignore, .prettierignore, packages/module-loader-commonjs/src/index.ts, rcgen.js
While server-side rendering Feature Apps in development mode, no changes to the Feature App code are visible in the rendered html, since the Feature App server bundle is always loaded from the require cache while the server is running. This fix ensures that no stale version of a fetched module is loaded from the require cache.
=> fix(module-loader-commonjs): avoid require cache

docs/guides/server-side-rendering.md, packages/demos/README.md, packages/demos/src/server-side-rendering/app.tsx, packages/demos/src/server-side-rendering/integrator.node.tsx, packages/demos/src/server-side-rendering/integrator.tsx, packages/demos/src/server-side-rendering/webpack-config.js, packages/demos/src/start-server.ts, packages/react/src/__tests__/feature-app-loader.node.test.tsx, packages/react/src/__tests__/feature-app-loader.test.tsx, packages/react/src/feature-app-loader.tsx, packages/react/src/feature-hub-context.tsx
With this feature, the integrator can prevent flickering when a server-rendered Feature App with external stylesheets is hydrated in the browser.
Normally, in the client, the `FeatureAppLoader` appends the stylesheets after it has been mounted. Since the integrator usually preloads Feature App client bundles before starting the hydration, the server-rendered Feature App HTML is displayed unstyled until the integrator client bundle as well as all Feature App client bundles have been loaded and evaluated.
Now, the integrator can collect all stylesheets during SSR, and append link elements for them to the document head, before sending the HTML to the client. This allows the browser to immediately load theses stylesheets before rendering the DOM, and thus prevents any flickering caused by …
=> feat(react): support adding Feature App stylesheets to the document during SSR

.travis.yml, package.json, scripts/ci/test-azure.sh, scripts/ci/test-travis.sh
Jest with webpack has known memory leaks, see facebook/jest#6399 for details. To put a bandaid on this issue, we run only two integration tests at once in the CI so that we don't run out of memory and still can add more integration tests later (vs. increasing `max_old_space_size`).
=> ci(all): run two integration tests at once to avoid memory leak issues

scripts/ci/test-azure.sh, scripts/ci/test-travis.sh, scripts/ci/test.sh
This is needed when there are is an odd number of integration tests. In this case the last one is run alone and jest stalls with this error:
> Jest did not exit one second after the test run has completed.
> This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
[Stalled pipeline example](https://dev.azure.com/feature-hub/feature-hub/_build/results?buildId=51)
=> ci(all): force exit on integration tests

.yarnclean, packages/demos/package.json, yarn.lock
To solve the incompatibility issues caused by getting `@types/react-native` with the newer version of `@types/styled-components`, we are using the 4th option suggested in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33015#issuecomment-488309875 as work-around.
=> build(demos): update @types/styled-components

packages/history-service/src/__tests__/create-root-location-transformer.test.ts, packages/history-service/src/create-root-location-transformer.ts
BREAKING CHANGE: The option `primaryConsumerUid` of `createRootLocationTransformer` has been renamed to `primaryConsumerId`.
=> feat(history-service): rename primaryConsumerUid to primaryConsumerId

packages/core/src/__tests__/feature-app-manager.test.ts, packages/core/src/feature-app-manager.ts, packages/core/src/feature-service-registry.ts, packages/demos/src/custom-logging/app.tsx, packages/demos/src/custom-logging/integrator.tsx, packages/react/src/__tests__/feature-app-container.node.test.tsx, packages/react/src/__tests__/feature-app-container.test.tsx, packages/react/src/feature-app-container.tsx, packages/react/src/feature-app-loader.tsx
fixes #490
BREAKING CHANGE: Instead of passing the `featureAppId` and the `featureServices` as separate arguments to the `beforeCreate` callback, the full Feature App environment, that contains the `featureAppId` and `featureServices`, is now passed as a single argument (`env`). This is the same argument that is passed to the Feature App's `create` method.
=> feat(all): pass full env to beforeCreate callback

packages/react/src/__tests__/feature-app-container.node.test.tsx, packages/react/src/__tests__/feature-app-loader.node.test.tsx, packages/react/src/feature-app-container.tsx, packages/react/src/feature-app-loader.tsx
BREAKING CHANGE: When the FeatureAppContainer/FeatureAppLoader catches a render error on the server, this error was previously re-thrown. To re-create this behavior, an `onError` prop must be defined that throws the error.
=> feat(react): do not re-throw render errors on server

packages/async-ssr-manager/src/index.ts, packages/core/src/externals-validator.ts, packages/core/src/feature-app-manager.ts, packages/core/src/feature-service-registry.ts, packages/history-service/src/define-history-service.ts, packages/react/src/feature-hub-context.tsx, packages/serialized-state-manager/src/index.ts, packages/server-request/src/index.ts
BREAKING CHANGE: The following interfaces have been removed:
- AsyncSsrManagerV0
- ExternalsValidatorLike
- FeatureAppManagerLike
- FeatureServiceRegistryLike
- HistoryServiceV0
- FeatureHubContextValue
- SerializedStateManagerV0
- ServerRequestV0
=> fix(all): remove all deprecated interfaces

packages/demos/src/history-service/root-location-transformer.ts, packages/history-service/src/__tests__/create-root-location-transformer.test.ts, packages/history-service/src/create-root-location-transformer.ts, packages/history-service/src/internal/history-multiplexer.ts, packages/history-service/src/internal/test-root-location-transformer.ts
BREAKING CHANGE: The `currentRootLocation` and `consumerLocation` parameters of `createRootLocation` have been switched.
=> fix(history-service): reorder createRootLocation params

packages/core/src/__tests__/create-feature-hub.test.ts, packages/core/src/__tests__/feature-app-manager.test.ts, packages/core/src/feature-app-manager.ts, packages/dom/src/feature-app-container.ts, packages/react/src/__tests__/feature-app-container.node.test.tsx, packages/react/src/__tests__/feature-app-container.test.tsx, packages/react/src/__tests__/feature-app-loader.node.test.tsx, packages/react/src/__tests__/feature-app-loader.test.tsx, packages/react/src/feature-app-container.tsx
fixes #505
BREAKING CHANGE: `FeatureAppManager#getFeatureAppScope` has been replaced by `FeatureAppManager#createFeatureAppScope`, since now a new `FeatureAppScope` is created for every call. When a Feature App is unmounted, the `release` method (previously called `destroy`) must be called. Only when all scopes for a Feature App ID have been released, the Feature App instance is destroyed.
=> fix(all): do not destroy Feature App when it is rendered multiple times

packages/demos/src/feature-app-in-feature-app/feature-app-inner.tsx, packages/demos/src/feature-app-in-feature-app/feature-app-outer.tsx
The error got into `master` with the release that was created by Travis (increasing the `@feature-hub/core` version). 🙄
=> fix(demos): increase feature-hub version in externals

docs/guides/feature-app-in-feature-app.md, docs/guides/sharing-npm-dependencies.md, packages/module-loader-commonjs/package.json, packages/module-loader-commonjs/src/__tests__/index.test.ts, packages/module-loader-commonjs/src/index.ts, yarn.lock
=> fix(module-loader-commonjs): avoid using fs to require commonjs module

packages/core/src/__tests__/feature-service-registry.test.ts, packages/core/src/feature-service-registry.ts
If a feature service with dependencies is registered and those dependencies have already been registered beforehand, do not log that those dependent feature services are already registered and can not be re-registered. They are not tried to be registered anyway.
=> fix(core): avoid wrong featureServiceAlreadyRegistered logs

packages/module-loader-commonjs/src/__tests__/index.test.ts, packages/module-loader-commonjs/src/index.ts
Dear Feature Hub team,
We at Das Büro am Draht need to load Feature Apps via proxy.
The dependency `node-fetch` does not consider proxy settings that are defined by environment variable (`process.env.HTTP_PROXY`).
Also, it seems that the team around `node-fetch` won't ever add proxy support. Please see this issue for further information: https://github.com/node-fetch/node-fetch/issues/195
So, with this pull request I add proxy support to the module loader by adding a proxy agent to the request.
What do you think? I hope you like the feature and its implementation.
Looking forward to hearing from you.
Thanks in advance and kind regards
Niels Garve (Das Büro am Draht)
=> feat(module-loader-commonjs): add proxy support

packages/core/.size-limit.js, packages/core/package.json, packages/core/src/externals-validator.ts, packages/core/src/feature-service-registry.ts, tslint.json, yarn.lock
This reduces the gzipped size fo `@feature-hub/core` by ~0.5 KB, which is not a lot but least something.
closes #130
=> fix(core): update semver to reduce size

packages/demos/src/start-server.js
Optional chaining is not supported in Node 12.
=> fix(demos): avoid optional chaining operator

packages/core/src/create-feature-hub.ts, packages/core/src/feature-app-manager.ts, packages/react/src/feature-app-loader.tsx, packages/react/src/feature-hub-context.tsx
- docs(core): add JSDoc comments for the new `moduleType` param
- docs(react): add JSDoc comments for the new `moduleType` param
=> Module federation loader JSDoc comments

packages/async-ssr-manager/src/__tests__/index.test.ts, packages/async-ssr-manager/src/index.ts, packages/async-ssr-manager/src/internal/async-ssr-manager.ts
We have discovered at the team that asynchronous rendering is necessary for things like https://www.apollographql.com/docs/react/api/react/ssr/#rendertostringwithdata. Therefore we have introduced support of asynchronous rendering to the `renderUntilCompleted`.
Example code:
```typescript
import { renderToStringWithData } from '@apollo/client/react/ssr';
//...
const content = await asyncSsrManager.renderUntilCompleted(() =>
renderToStringWithData(
<React.StrictMode>
<ApolloProvider client={client}>
<StyleSheetManager sheet={sheet.instance}>
<FeatureHubContextProvider value={featureHubContextValue}>
<App />
</FeatureHubContextProvider>
</StyleSheetManager>
</ApolloProvider>
</React.StrictMode>
)
);
const serializedStates = serializedStateManager.serializeStates();
const html = (
<Html …
```
=> Enable async render inside renderUntilCompleted

packages/core/src/feature-app-manager.ts, packages/react/src/feature-app-loader.tsx, packages/react/src/internal/internal-feature-app-container.tsx
With this a feature app can include some other FA to select
something and the new FA can signal in the done call if
changes should be applied or if it just terminated and
nothing should be changed
=> feat(all): add failure option to done call

packages/react/src/__tests__/feature-app-container.test.tsx, packages/react/src/__tests__/feature-app-loader.test.tsx, packages/react/src/feature-app-loader.tsx, packages/react/src/internal/internal-feature-app-container.tsx
BREAKING CHANGE: Removed `renderError` prop. Use the `children` prop instead.
=> fix(react): remove deprecated `renderError` prop

.github/workflows/ci.yml
e.g.: https://github.com/sinnerschrader/feature-hub/actions/runs/6349645512/job/17248138106
=> ci(all): turns out, in the CI we do need more memory for the itests

.size-limit.js, packages/module-loader-amd/package.json, packages/module-loader-amd/src/index.ts, yarn.lock
fixes #80
Note that the breaking change mentioned in #80 is no longer required (see also https://github.com/systemjs/systemjs#compatibility-with-webpack).
=> feat(module-loader-amd): update SystemJS

packages/core/src/__tests__/create-feature-hub.test.ts, packages/core/src/__tests__/externals-validator.test.ts, packages/core/src/__tests__/feature-app-manager.test.ts, packages/core/src/__tests__/feature-service-registry.test.ts, packages/core/src/externals-validator.ts, packages/core/src/feature-app-manager.ts, packages/core/src/feature-service-registry.ts
This is especially useful if the externals validator is replaced by a custom one that needs the consumer info for logging purposes.
=> feat(core): include consumer ID in externals validation

packages/async-ssr-manager/package.json, packages/core/package.json, packages/dom/package.json, packages/history-service/package.json, packages/logger/package.json, packages/module-loader-amd/package.json, packages/module-loader-commonjs/package.json, packages/module-loader-federation/package.json, packages/react/package.json, packages/serialized-state-manager/package.json, packages/server-request/package.json
The `"exports"` field takes precedence over the `"main"` field (see https://nodejs.org/api/packages.html#package-entry-points). So when a feature hub module is required in Node.js, we need to make sure to include the CJS entries in the conditional exports. Otherwise Node.js would fail to require the default ESM entries (`SyntaxError: Unexpected token 'export'`).
=> fix(all): use `import`/`require` instead of `default` in `exports`

packages/module-loader-amd/src/index.ts
Turns out, #772 did not cover all cases. When a Feature App is build with Webpack and the babel loader, it looks like this:
This case is not covered by our previous check whether `default` is a `Module`. Instead, we now do what Webpack (among others) does, and look for the presence of the `__esModule` property to decide whether to use `module.default` or `module`.
=> fix(module-loader-amd): use `__esModule` as default condition

packages/core/src/__tests__/feature-service-registry.test.ts, packages/core/src/feature-service-registry.ts
This method is useful when you want to log the currently registered feature services with their provided versions.
=> feat(core): add `getInfo` method to feature service registry
