sinnerschrader/feature-hub

- .travis.yml
- README.md
- scripts/release.sh
encrypted with `--com` this time 🤦‍♂️
> ci(all): setup npm release

- examples/todomvc-footer/package.json
- examples/todomvc-footer/postcss.config.js
- examples/todomvc-footer/tsconfig.json
- examples/todomvc-footer/webpack.config.js
- yarn.lock
> build(examples): switch TodoMVC footer to webpack

- examples/todomvc-header/package.json
- examples/todomvc-header/tsconfig.json
- examples/todomvc-header/webpack.config.js
- yarn.lock
> build(examples): switch TodoMVC header to webpack

- README.md
- scripts/ci/test.sh
> docs(all): fix API links in main README

- README.md
- jest.config.js
- packages/history-service/README.md
- packages/history-service/package.json
- packages/history-service/src/__tests__/index.test.ts
- packages/history-service/src/__tests__/root-location-transformer.test.ts
- packages/history-service/src/base-history.ts
- packages/history-service/src/browser-history.ts
- packages/history-service/src/index.ts
- packages/history-service/src/memory-history.ts
- packages/history-service/src/root-location-transformer/consumer-paths.ts
- packages/history-service/src/root-location-transformer/index.ts
- packages/history-service/tsconfig.build.json
- packages/history-service/tsconfig.json
- packages/history-service/tslint.json
- packages/server-renderer/src/__tests__/index.test.ts
- tslint.json
- yarn.lock
closes #21 
@clebert Please review the documentation.
> feat(history-service): add history feature service

- scripts/ci/release.sh
https://github.com/lerna/lerna/tree/master/commands/version#--push
> ci(all): only push to git when publish succeeded

- README.md
- packages/integration-tests/tslint.json
- packages/react/src/__tests__/feature-app-container.node.test.tsx
- packages/react/src/__tests__/feature-app-container.test.tsx
- packages/react/src/__tests__/feature-app-loader.node.test.tsx
- packages/react/src/__tests__/feature-app-loader.test.tsx
- tslint.json
> docs(all): providing config objects as an integrator

- packages/demos/package.json
- packages/history-service/.size-limit.js
- packages/history-service/package.json
> feat(history-service): history is now a peer dependency

- README.md
- packages/core/src/__tests__/feature-app-manager.test.ts
- packages/core/src/__tests__/feature-service-registry.test.ts
- packages/core/src/feature-app-manager.ts
- packages/core/src/feature-service-registry.ts
- packages/demos/src/amd-module-loader/integrator.tsx
- packages/demos/src/history-service/integrator.tsx
> feat(core): both the manager and the registry now accept options

- packages/react/src/__tests__/feature-app-loader.test.tsx
- packages/react/src/feature-app-loader.tsx
> feat(react): the loader will not try to load an empty src

- packages/core/package.json
> build(core): add keywords to the package.json file

- packages/react/src/__tests__/feature-app-loader.node.test.tsx
- packages/react/src/__tests__/feature-app-loader.test.tsx
- packages/react/src/feature-app-loader.tsx
> feat(react): improve log messages to make them more consistent

- packages/demos/package.json
- packages/demos/src/history-service/history-consumer-definition.tsx
- packages/demos/src/history-service/history-consumer.tsx
- packages/demos/src/history-service/integrator.tsx
- packages/demos/src/start-server.ts
- yarn.lock
> feat(demos): add push/replace UI for further history-service itest scenarios

- README.md
> docs(all): add another property of Feature Services

- README.md
- packages/history-service/README.md
> docs(all): add history service abstract to main README

- jest.config.js
- packages/demos/README.md
- packages/demos/src/commonjs-module-loader/feature-app.tsx
- packages/demos/src/commonjs-module-loader/index.test.ts
- packages/demos/src/commonjs-module-loader/integrator.node.tsx
- packages/demos/src/commonjs-module-loader/integrator.ts
- packages/demos/src/commonjs-module-loader/webpack-config.ts
- packages/demos/src/history-service/index.test.ts
- packages/demos/src/start-server.ts
- packages/demos/src/watch-demo.ts
- packages/module-loader/index.d.ts
- packages/module-loader/index.js
- packages/module-loader/node.d.ts
- packages/module-loader/node.js
- packages/module-loader/package.json
- packages/module-loader/src/node.ts
- scripts/ci/test.sh
- tsconfig.json
There is also a new demo for the commonjs module loader.
> feat(module-loader): use standard package entry for node module loader

- README.md
- docs/getting-started/demos.md
- docs/guides/integrating-the-feature-hub.md
- docs/guides/sharing-the-browser-history.md
- docs/guides/writing-a-feature-app.md
- packages/demos/README.md
- packages/website/sidebars.json
> docs(all): add demos page to website

- packages/react/src/__tests__/feature-app-container.node.test.tsx
- packages/react/src/__tests__/feature-app-container.test.tsx
- packages/react/src/__tests__/feature-app-loader.node.test.tsx
- packages/react/src/__tests__/feature-app-loader.test.tsx
- packages/react/src/feature-app-container.tsx
- packages/react/src/feature-app-loader.tsx
- The messages/errors logged by the React `FeatureAppContainer` have been improved.
- The messages/errors logged by the React `FeatureAppLoader` have been improved.
> feat(react): improve logging

- docs/guides/integrating-the-feature-hub.md
- packages/demos/src/commonjs-module-loader/integrator.node.tsx
- packages/react/src/__tests__/feature-app-loader.node.test.tsx
- packages/react/src/feature-app-loader.tsx
> refactor(react): rename nodeSrc to serverSrc

- docs/getting-started/introduction.md
- packages/website/siteConfig.js
- packages/website/static/external-sidebar-links.js
- packages/website/static/index.css
> docs(all): enable search on website

- packages/react/package.json
- packages/react/src/__tests__/feature-app-loader.node.test.tsx
- packages/react/src/__tests__/feature-app-loader.test.tsx
- packages/react/src/feature-app-loader.tsx
> feat(react): add asyncSsrManager prop to FeatureAppLoader

- docs/guides/sharing-the-browser-history.md
- packages/async-ssr-manager/src/__tests__/index.test.ts
- packages/async-ssr-manager/src/index.ts
- packages/async-ssr-manager/src/internal/async-ssr-manager.ts
- packages/core/src/feature-app-manager.ts
- packages/core/src/feature-service-registry.ts
- packages/demos/src/async-ssr-manager/integrator.node.tsx
- packages/history-service/package.json
- packages/history-service/src/__tests__/define-history-service.node.test.ts
- packages/history-service/src/__tests__/define-history-service.test.ts
- packages/history-service/src/define-history-service.ts
- packages/history-service/src/internal/create-history-multiplexers.ts
- packages/history-service/src/internal/static-root-history.ts
- packages/react/src/__tests__/feature-app-loader.node.test.tsx
- packages/react/src/__tests__/feature-app-loader.test.tsx
- packages/server-request/src/__tests__/index.test.ts
- packages/server-request/src/index.ts
Instead the server request Feature Service should be used.
fixes #260
> feat(async-ssr-manager): remove the serverRequest property

- packages/async-ssr-manager/package.json
- packages/async-ssr-manager/src/__tests__/index.test.ts
- packages/core/package.json
- packages/core/src/__tests__/feature-app-manager.test.ts
- packages/core/src/__tests__/feature-service-registry.test.ts
- packages/history-service/package.json
- packages/history-service/src/__tests__/define-history-service.node.test.ts
- packages/history-service/src/__tests__/define-history-service.test.ts
- packages/react/package.json
- packages/react/src/__tests__/feature-app-container.node.test.tsx
- packages/react/src/__tests__/feature-app-container.test.tsx
- packages/react/src/__tests__/feature-app-loader.node.test.tsx
- packages/react/src/__tests__/feature-app-loader.test.tsx
- yarn.lock
> test(all): use jest-stub-methods for console

- packages/core/src/feature-service-registry.ts
> docs(core): add jsdoc to FeatureServiceRegistry

- docs/guides/server-side-rendering-using-react.md
- packages/async-ssr-manager/README.md
- packages/async-ssr-manager/src/index.ts
> docs(async-ssr-manager): add JSDoc comments

- package.json
- packages/demos/package.json
- yarn.lock
> build(demos): remove fix typescript@3.1.6 dependency

- packages/react/src/feature-app-container.tsx
- packages/react/src/feature-app-loader.tsx
We decided that this feature is implementable for the integrator with reasonable effort without changes to the feature-hub/react package.
> fix(react): remove mission critical feature app todos

- packages/demos/src/history-service/index.test.ts
- packages/demos/src/module-loader-amd/index.test.ts
- packages/demos/src/module-loader-commonjs/index.test.ts
- packages/demos/src/server-side-rendering/index.test.ts
On Travis the bundling takes a very long time.
> fix(demos): increase jest timeout to 120 seconds

- docs/guides/server-side-rendering.md
> docs(website): add note to SSR guide regarding async operations

- docs/guides/feature-app-in-feature-app.md
- docs/help/faq.md
- packages/website/sidebars.json
[Rendered guide](https://deploy-preview-319--feature-hub.netlify.com/docs/guides/feature-app-in-feature-app)
> docs(website): add "Feature App in Feature App" guide

- docs/guides/integrating-the-feature-hub.md
- docs/guides/server-side-rendering.md
- docs/guides/sharing-the-browser-history.md
- packages/react/src/feature-app-loader.tsx
- packages/react/src/feature-hub-context.tsx
[Rendered Guide](https://deploy-preview-324--feature-hub.netlify.com/docs/guides/server-side-rendering#preloading-feature-apps-on-the-client)
closes #27
> docs(website): write preloading section in SSR guide

- docs/guides/integrating-the-feature-hub.md
- docs/guides/server-side-rendering.md
- docs/guides/sharing-the-browser-history.md
- docs/guides/writing-a-feature-app.md
- docs/guides/writing-a-feature-service.md
> docs(website): update docs for dependencies

- packages/core/src/__tests__/feature-service-registry.test.ts
- packages/core/src/feature-service-registry.ts
- packages/demos/src/feature-app-in-feature-app/integrator.node.tsx
- packages/demos/src/feature-app-in-feature-app/integrator.tsx
- packages/demos/src/history-service/integrator.node.tsx
- packages/demos/src/history-service/integrator.tsx
- packages/demos/src/module-loader-amd/integrator.tsx
- packages/demos/src/module-loader-commonjs/integrator.node.tsx
- packages/demos/src/server-side-rendering/integrator.node.tsx
- packages/demos/src/server-side-rendering/integrator.tsx
> feat(core): make ExternalsValidator optional for the FeatureServiceRegistry

- packages/async-ssr-manager/package.json
- packages/core/package.json
- packages/dom/package.json
- packages/history-service/package.json
- packages/module-loader-amd/package.json
- packages/module-loader-commonjs/package.json
- packages/react/package.json
- packages/serialized-state-manager/package.json
- packages/server-request/package.json
see also https://webpack.js.org/guides/tree-shaking/
> fix(all): add missing sideEffects package.json entries

- docs/guides/writing-a-feature-service.md
[Rendered](https://deploy-preview-393--feature-hub.netlify.com/docs/guides/writing-a-feature-service)
> docs(website): semver caret ranges for feature service dependencies

- docs/getting-started/demos.md
[Rendered](https://deploy-preview-391--feature-hub.netlify.com/docs/getting-started/demos)
> docs(website): describe and link to todomvc live demo

- packages/core/src/__tests__/create-feature-hub.test.ts
- packages/core/src/__tests__/feature-app-manager.test.ts
- packages/core/src/__tests__/feature-service-registry.test.ts
- packages/core/src/create-feature-hub.ts
- packages/core/src/feature-app-manager.ts
- packages/core/src/feature-service-registry.ts
- packages/core/src/index.ts
- packages/core/src/logger.ts
> feat(core): add logger option to FeatureAppManager, FeatureServiceRegistry, and createFeatureHub

- packages/react/src/__tests__/feature-app-container.test.tsx
- packages/react/src/__tests__/feature-app-loader.test.tsx
- packages/react/src/__tests__/logger.ts
- packages/react/src/feature-app-container.tsx
- packages/react/src/feature-app-loader.tsx
- packages/react/src/feature-hub-context.tsx
The `FeatureHubContext` provides the custom logger to the `FeatureAppLoader` and `FeatureAppContainer`.
> feat(react): add custom logger option to FeatureHubContext

- docs/guides/integrating-the-feature-hub.md
- docs/guides/server-side-rendering.md
- docs/guides/sharing-the-browser-history.md
- docs/guides/writing-a-feature-app.md
- docs/guides/writing-a-feature-service.md
- packages/website/static/index.css
> fix(website): improve visibility of note boxes

- docs/getting-started/api.md
[Rendered](https://deploy-preview-422--feature-hub.netlify.com/docs/getting-started/api)
> docs(website): add link to logger api docs

- docs/guides/custom-logging.md
- packages/website/sidebars.json
[Rendered](https://deploy-preview-423--feature-hub.netlify.com/docs/guides/custom-logging)
> docs(website): add custom logging guide

- README.md
- docs/getting-started/introduction.md
- packages/dom/README.md
- packages/react/README.md
> docs(website): improve Feature Hub introduction

- docs/help/faq.md
[Rendered FAQ Entry](https://deploy-preview-460--feature-hub.netlify.com/docs/help/faq#does-the-feature-hub-run-in-internet-explorer-11-ie11)
closes #455
closes #457
> docs(website): document IE11 support

- packages/demos/README.md
- packages/demos/src/react-error-handling/feature-app.ts
- packages/demos/src/react-error-handling/index.test.ts
- packages/demos/src/react-error-handling/integrator.tsx
- packages/demos/src/react-error-handling/webpack-config.js
> feat(demos): add React Error Handling demo

- packages/demos/src/feature-app-in-feature-app/index.test.ts
- packages/demos/src/history-service/index.test.ts
- packages/demos/src/integrator-dom/index.test.ts
- packages/demos/src/module-loader-amd/index.test.ts
- packages/demos/src/module-loader-commonjs/index.test.ts
- packages/demos/src/react-error-handling/index.test.ts
- packages/demos/src/server-side-rendering/index.test.ts
> test(demos): increase timeout to 120 s

- docs/guides/writing-a-feature-app.md
- docs/guides/writing-a-feature-service.md
- packages/core/src/__tests__/feature-service-registry.test.ts
- packages/core/src/feature-service-registry.ts
> fix(core): coerce dependency versions to caret ranges

- packages/react/src/__tests__/feature-app-container.test.tsx
- packages/react/src/internal/internal-feature-app-container.tsx
> fix(react): do not set state after FeatureAppContainer has been unmounted

- babel.config.js
- package.json
- packages/core/src/__tests__/feature-app-manager.test.ts
- packages/core/src/feature-app-manager.ts
- packages/core/src/internal/feature-app-manager-messages.ts
- packages/demos/README.md
- packages/demos/src/app-renderer.d.ts
- packages/demos/src/module-loader-federation/webpack-config.js
- packages/demos/src/server-side-rendering/app.tsx
- packages/demos/src/server-side-rendering/feature-app.tsx
- packages/demos/src/server-side-rendering/hello-world.tsx
- packages/demos/src/server-side-rendering/integrator.node.tsx
- packages/demos/src/server-side-rendering/integrator.tsx
- packages/demos/src/server-side-rendering/webpack-config.js
- packages/demos/src/start-server.js
- packages/react/src/__tests__/feature-app-loader.node.test.tsx
- packages/react/src/feature-app-loader.tsx
- packages/react/src/feature-hub-context.tsx
- tslint.json
- fix(all): handle module type during hydration
- refactor(core): extract error message
> Handle module type during hydration

- docs/guides/integrating-the-feature-hub.md
- docs/guides/server-side-rendering.md
- https://2c59e34e.feature-hub.io/docs/guides/integrating-the-feature-hub
- https://2c59e34e.feature-hub.io/docs/guides/server-side-rendering#handling-module-types
> docs(all): handling module types from the integrator's perspective

- .gitignore
- docs/guides/feature-app-in-feature-app.md
- docs/guides/integrating-the-feature-hub.md
- docs/guides/reducing-the-bundle-size.md
- docs/guides/sharing-npm-dependencies.md
- docs/guides/writing-a-feature-app.md
- docs/help/faq.md
- packages/async-ssr-manager/README.md
- packages/core/README.md
- packages/demos/src/module-loader-commonjs/integrator.node.tsx
- packages/demos/src/module-loader-commonjs/webpack-config.js
- packages/demos/src/module-loader-multiple/webpack-config.js
- packages/dom/README.md
- packages/history-service/README.md
- packages/logger/README.md
- packages/module-loader-amd/README.md
- packages/module-loader-commonjs/README.md
- packages/module-loader-federation/README.md
- packages/react/README.md
- packages/serialized-state-manager/README.md
- packages/server-request/README.md
- packages/website/siteConfig.js
- packages/website/static/index.css
- https://bbc112bb.feature-hub.io/docs/guides/writing-a-feature-app
- https://bbc112bb.feature-hub.io/docs/guides/sharing-npm-dependencies
> Document Bundling

- docs/guides/integrating-the-feature-hub.md
- docs/guides/reducing-the-bundle-size.md
- docs/help/faq.md
- https://09903b5a.feature-hub.io/docs/guides/reducing-the-bundle-size
- https://09903b5a.feature-hub.io/docs/help/faq#does-the-feature-hub-run-in-internet-explorer-11-ie11
> docs(all): document `publicPath` constraints

- docs/guides/server-side-rendering.md
- packages/demos/src/server-side-rendering/integrator.tsx
- packages/serialized-state-manager/src/__tests__/index.test.ts
- packages/serialized-state-manager/src/index.ts
Motivated by https://github.com/sinnerschrader/feature-hub/issues/706#issuecomment-1042920662
TODOs:
> feat(serialized-state-manager): introduce a definition factory function

- docs/guides/sharing-the-browser-history.md
- packages/core/src/__tests__/create-feature-hub.test.ts
- packages/core/src/__tests__/feature-app-manager.test.ts
- packages/core/src/create-feature-hub.ts
- packages/core/src/feature-app-manager.ts
> feat(core): introduce onBind callback

- packages/react/src/__tests__/feature-app-loader-and-container.test.tsx
- packages/react/src/internal/internal-feature-app-container.tsx
closes #711 
Co-authored-by: Lasse Kuechler <lasse.kuechler@sinnerschrader.com>
> fix(react): attach DOM Feature App after Feature App Definiton is loaded asynchronously

- packages/core/src/__tests__/create-feature-hub.test.ts
- packages/core/src/__tests__/feature-app-manager.test.ts
- packages/core/src/create-feature-hub.ts
- packages/core/src/feature-app-manager.ts
- packages/react/src/__tests__/feature-app-container.test.tsx
- packages/react/src/feature-app-container.tsx
- packages/react/src/feature-app-loader.tsx
- packages/react/src/internal/feature-app-context.ts
- packages/react/src/internal/internal-feature-app-container.tsx
This allows the integrator to collect information about "Feature App in Feature App" usage.
> feat(all): pass `parentFeatureApp` into `onBind`

- package.json
- yarn.lock
> build(all): update typescript to v5.2

- package.json
Hopefully the fixes the CI flakyness.
> build(all): increase memory for integration tests

- package.json
- packages/demos/src/feature-app-in-feature-app/index.test.ts
- packages/demos/src/module-loader-amd/index.test.ts
- packages/demos/src/module-loader-commonjs/index.test.ts
- packages/demos/src/module-loader-federation/index.test.ts
- packages/demos/src/module-loader-multiple/index.test.ts
- packages/demos/src/server-side-rendering/index.test.ts
- packages/demos/src/start-server.js
See commit messages for details.
> A couple of integration test improvements

- package.json
- yarn.lock
see https://github.com/clebert/aws-simple/pull/179
> ci(all): update aws-simple to fix cleanup job
